export const RESP = {
	BULK: '$',
	ARRAY: '*',
	STRING: '+',
	ERROR: '-',
	INT: ':',
	NULL: '_',
	ATTRIBUTE: '|',
};
export const RESP_U8 = {
	BULK: 36,
	ARRAY: 42,
	STRING: 43,
	ERROR: 45,
	INT: 58,
	NULL: 95,
	ATTRIBUTE: 124,
};
export const RESP_SPLIT = '\r\n';

export type KeyPattern = number[] | 'even' | 'all';

// Maps a command to which of its arguments (0-based, command name excluded) are keys.
// 'all' = every argument is a key; 'even' = arguments at positions 0, 2, 4, ... are keys.
export const KEY_POSITIONS: Record<string, KeyPattern> = {
	get: [0],
	getset: [0],
	getdel: [0],
	getex: [0],
	set: [0],
	setnx: [0],
	setex: [0],
	psetex: [0],
	append: [0],
	strlen: [0],
	getrange: [0],
	setrange: [0],
	incr: [0],
	decr: [0],
	incrby: [0],
	decrby: [0],
	incrbyfloat: [0],
	setbit: [0],
	getbit: [0],
	bitcount: [0],
	bitpos: [0],
	bitfield: [0],
	expire: [0],
	pexpire: [0],
	expireat: [0],
	pexpireat: [0],
	expiretime: [0],
	pexpiretime: [0],
	ttl: [0],
	pttl: [0],
	persist: [0],
	type: [0],
	dump: [0],
	hget: [0],
	hset: [0],
	hsetnx: [0],
	hmset: [0],
	hmget: [0],
	hdel: [0],
	hgetall: [0],
	hkeys: [0],
	hvals: [0],
	hlen: [0],
	hexists: [0],
	hincrby: [0],
	hincrbyfloat: [0],
	hstrlen: [0],
	hscan: [0],
	hrandfield: [0],
	lpush: [0],
	rpush: [0],
	lpushx: [0],
	rpushx: [0],
	lpop: [0],
	rpop: [0],
	lrange: [0],
	llen: [0],
	lindex: [0],
	lset: [0],
	linsert: [0],
	lrem: [0],
	ltrim: [0],
	lpos: [0],
	sadd: [0],
	srem: [0],
	smembers: [0],
	sismember: [0],
	smismember: [0],
	scard: [0],
	spop: [0],
	srandmember: [0],
	sscan: [0],
	zadd: [0],
	zrem: [0],
	zscore: [0],
	zmscore: [0],
	zrange: [0],
	zrangebyscore: [0],
	zrangebylex: [0],
	zrevrange: [0],
	zrevrangebyscore: [0],
	zrank: [0],
	zrevrank: [0],
	zcard: [0],
	zcount: [0],
	zlexcount: [0],
	zincrby: [0],
	zscan: [0],
	zpopmin: [0],
	zpopmax: [0],
	zrandmember: [0],
	zrangestore: [0, 1],
	bitfield_ro: [0],
	xadd: [0],
	xlen: [0],
	xrange: [0],
	xrevrange: [0],
	xdel: [0],
	xtrim: [0],
	xack: [0],
	xclaim: [0],
	xautoclaim: [0],
	restore: [0],
	move: [0],
	geoadd: [0],
	geopos: [0],
	geodist: [0],
	geohash: [0],
	geosearch: [0],
	pfadd: [0],
	rename: [0, 1],
	renamenx: [0, 1],
	copy: [0, 1],
	smove: [0, 1],
	lmove: [0, 1],
	rpoplpush: [0, 1],
	blmove: [0, 1],
	brpoplpush: [0, 1],
	lcs: [0, 1],
	del: 'all',
	unlink: 'all',
	touch: 'all',
	exists: 'all',
	watch: 'all',
	mget: 'all',
	sinter: 'all',
	sunion: 'all',
	sdiff: 'all',
	pfcount: 'all',
	pfmerge: 'all',
	mset: 'even',
	msetnx: 'even',
};

// Commands whose key positions depend on argument values (a numkeys count, a subcommand,
// or a trailing STORE clause) and so cannot be expressed as fixed positions.
export type VariadicSpec =
	| { kind: 'restFrom'; from: number } // every argument from `from` to the end is a key
	| { kind: 'restButLast'; from: number } // keys from `from` to the second-to-last argument (last is a timeout)
	| { kind: 'numkeyed'; countAt: number; extraKeys?: number[] } // a count at `countAt` precedes that many keys
	| { kind: 'subcommandKey'; keyAt: number; subcommands: string[] } // key at `keyAt` only for the listed subcommands
	| { kind: 'sort'; first: number } // key at `first`, plus every BY/GET/STORE pattern (excluding the GET `#` self reference)
	| { kind: 'radiusStore'; first: number } // key at `first`, plus each STORE/STOREDIST destination
	| { kind: 'streams' } // the keys half of the `STREAMS key… id…` tail (XREAD / XREADGROUP)
	| { kind: 'migrate' }; // key at index 2, or every key after a KEYS clause (multi-key MIGRATE)

export const KEY_RESOLVERS: Record<string, VariadicSpec> = {
	bitop: { kind: 'restFrom', from: 1 },
	blpop: { kind: 'restButLast', from: 0 },
	brpop: { kind: 'restButLast', from: 0 },
	bzpopmin: { kind: 'restButLast', from: 0 },
	bzpopmax: { kind: 'restButLast', from: 0 },
	lmpop: { kind: 'numkeyed', countAt: 0 },
	zmpop: { kind: 'numkeyed', countAt: 0 },
	blmpop: { kind: 'numkeyed', countAt: 1 },
	bzmpop: { kind: 'numkeyed', countAt: 1 },
	zunion: { kind: 'numkeyed', countAt: 0 },
	zinter: { kind: 'numkeyed', countAt: 0 },
	zdiff: { kind: 'numkeyed', countAt: 0 },
	sintercard: { kind: 'numkeyed', countAt: 0 },
	zunionstore: { kind: 'numkeyed', countAt: 1, extraKeys: [0] },
	zinterstore: { kind: 'numkeyed', countAt: 1, extraKeys: [0] },
	zdiffstore: { kind: 'numkeyed', countAt: 1, extraKeys: [0] },
	sort: { kind: 'sort', first: 0 },
	sort_ro: { kind: 'sort', first: 0 },
	object: { kind: 'subcommandKey', keyAt: 1, subcommands: ['encoding', 'refcount', 'idletime', 'freq'] },
	memory: { kind: 'subcommandKey', keyAt: 1, subcommands: ['usage'] },
	georadius: { kind: 'radiusStore', first: 0 },
	georadiusbymember: { kind: 'radiusStore', first: 0 },
	xread: { kind: 'streams' },
	xreadgroup: { kind: 'streams' },
	xgroup: { kind: 'subcommandKey', keyAt: 1, subcommands: ['create', 'setid', 'destroy', 'createconsumer', 'delconsumer'] },
	migrate: { kind: 'migrate' },
};

export const KEY_COMMANDS = [...Object.keys(KEY_POSITIONS), ...Object.keys(KEY_RESOLVERS)];
